# Generated by Django 6.0.8 on 2026-09-24 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='scripe_price_id',
            new_name='stripe_price_id',
        ),
    ]
